[scaffold]
version = "0.1.1"
cache_root = "/home/vpavlin/.cache/logos-scaffold"

[repos.lez]
url = "https://github.com/logos-blockchain/logos-execution-zone.git"
source = "https://github.com/logos-blockchain/logos-execution-zone.git"
path = "/home/vpavlin/.cache/logos-scaffold/repos/lez/35d8df0d031315219f94d1546ceb862b0e5b208f"
pin = "35d8df0d031315219f94d1546ceb862b0e5b208f"

[wallet]
home_dir = ".scaffold/wallet"

[framework]
kind = "default"
version = "0.1.0"

[framework.idl]
spec = "lssa-idl/0.1.0"
path = "idl"

[localnet]
port = 3040
risc0_dev_mode = true
